### ISSUE TITLE
2 of 1307 pulblishers not apparent during period when sync is disabled.

### ISSUE THREAD

**Issue by alexlydiate** [IATI/IATI-Validator-Server#19]
Describe the bug
Looking at the https://iativalidator.iatistandard.org/organisations it no longer seems to be in sync with the IATI Registry? The Registry holds 1307 publishers, while the Validator hold 1305.

To Reproduce

Go to 'https://iativalidator.iatistandard.org/organisations'
Look at orgs found'see: "Found 1305 organisations."'
Now go to down to 'https://iatiregistry.org/ '
Click on 'see: "1307 Organisations have published so far."'
Expected behavior
I would expect the Validator to be in sync with the IATI Registry

**Comment by siemvaessen** [comment]
Thanks for moving!

**Comment by siemvaessen** [comment]
1308 actual on the[ IATI Registry ](https://iatiregistry.org/)vs [1305 on the current Validator.](https://iativalidator.iatistandard.org/organisations) (just keeping track of the numbers)

**Comment by siemvaessen** [comment]
1309 on the Registry vs 1305 on the Validator.

**Comment by siemvaessen** [comment]
**~update** 1310 on the Registry vs 1305 on the Validator

**Comment by alexlydiate** [comment]
1310 on the Registry vs...1310 on the Validator. An equalizer! Better than the Euros this, isn't it?

That because, as I mentioned, the syncs were disabled. All are now on, and thus the Publishers are matching the Registry. That sync happens once an hour, so from here on we wouldn't expect it to be more than a couple of hours behind, if that.
